name: Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Python backend and ReactJS frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
       

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
  
  compile:
    name: Compile Program
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile program
        run: make program

  run:
    name: Run Program
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run program
        run: ./program
