Here is the detailed workflow YAML file you requested:

```yaml
name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Python backend and ReactJS frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
       
      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python Backend tests
        run: python manage.py test

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Frontend Requirements
        run: |
          cd frontend
          npm install

      - name: Test React App
        run: |
          cd frontend
          npm test

      - name: Build React App
        run: |
          cd frontend
          npm run build

  compile:
    name: Compile Program
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile program
        run: make program

  run:
    name: Run Program
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run program
        run: ./program
```

This YAML file describes a workflow with three jobs: `build`, `compile` and `run`. The `build` job will setup Python and NodeJS,